name: Daily Random Commits

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  random-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate random number of commits (1–3, weighted)
        run: |
          COMMITS=$(awk 'BEGIN {
            srand(); 
            r=int(rand()*100); 
            if (r < 70) print 1;
            else if (r < 90) print 2;
            else print 3;
          }')
          echo "Will make $COMMITS commit(s)"
          
          git config user.name "Saeed X4"
          git config user.email "saeed.sharifzadeh91@gmail.com"
          
          for i in $(seq 1 $COMMITS); do
            echo "$(date) - Commit $i" >> daily-log.txt
            git add daily-log.txt
            git commit -m "Daily random commit $i - $(date)"
          done

          git push
