name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          echo "$(date)" >> daily-log.txt
          git config user.name "Saeed X4"
          git config user.email "saeed.sharifzadeh91@gmail.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date)"
          git push
